name: Matrix Calculator CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clean any existing build files
      run: |
        rm -rf build
        find . -name "CMakeCache.txt" -delete
        find . -name "CMakeFiles" -type d -exec rm -rf {} + 2>/dev/null || true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ git build-essential

    - name: Install Google Test
      run: |
        git clone https://github.com/google/googletest.git -b release-1.13.0
        cd googletest
        mkdir build && cd build
        cmake ..
        make
        sudo make install

    - name: Configure project
      run: cmake -B build

    - name: Build project
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        ctest --verbose

    - name: Generate documentation
      run: |
        sudo apt-get install -y doxygen graphviz
        doxygen Doxyfile
        ls -la docs/html/
